name: publish

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    environment: nodejs
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"
      - name: Install deps
        run: pnpm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: publish-npm
        # run: pnpm publish --access public
        run: echo "test"
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
